package MailClient;

import Database.QuerySubmitter;
import MailPackage.Message;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * This class is the GUI for sending messages
 * @author Bryce, Steven, Hunter, Tristan
 */
public class SndMessageGUI extends javax.swing.JFrame {

    /**
     * Creates new form MessageGUI in case of new message
     */
    public SndMessageGUI() {
        initComponents();
        query = QuerySubmitter.getInstance();
        fromText.setText(query.getUser());
        fromText.setEditable(false);

    }
    
     /**
     * Creates new form MessageGUI in case of getting from outbox or replying 
     * to message
     * @param msg - Message to populate gui with
     * @param isReply - bool set to true if new message is a reply
     */
    public SndMessageGUI(Message msg, boolean isReply) {
        initComponents();
        query = QuerySubmitter.getInstance();

        //In reply case, set the body to the previous conversation at bottom of text area
        if(isReply) {
        fromText.setText(msg.mTo[0]);
        fromText.setEditable(false);
        toText.setText(msg.mFrom);
        subjectText.setText("re:" + msg.mSubject);
        bodyTextArea.setText(
                "\n\n\n\n******************************************************\n"
                + "Message sent by "
                + msg.mFrom + " on " + msg.mTimestamp.toString() 
                + "\n******************************************************\n"
                + msg.mBody);
        } else {
            //Otherwise this is a message in outbox, and just populate with current body
            subjectText.setText(msg.mSubject);
            bodyTextArea.setText(msg.mBody);
                    fromText.setText(msg.mFrom);
        fromText.setEditable(false);
        toText.setText(msg.mTo[0]);
        }
        bodyTextArea.setCaretPosition(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MessagePanel = new javax.swing.JPanel();
        toText = new javax.swing.JTextField();
        toLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bodyTextArea = new javax.swing.JTextArea();
        fromText = new javax.swing.JTextField();
        fromLabel = new javax.swing.JLabel();
        sendButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        subjectText = new javax.swing.JTextField();
        subjectLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        toLabel.setText("TO:");

        bodyTextArea.setColumns(20);
        bodyTextArea.setLineWrap(true);
        bodyTextArea.setRows(5);
        bodyTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(bodyTextArea);

        fromLabel.setText("FROM:");

        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        subjectLabel.setText("SUBJECT:");

        javax.swing.GroupLayout MessagePanelLayout = new javax.swing.GroupLayout(MessagePanel);
        MessagePanel.setLayout(MessagePanelLayout);
        MessagePanelLayout.setHorizontalGroup(
            MessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MessagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addGroup(MessagePanelLayout.createSequentialGroup()
                        .addGroup(MessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(toLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fromLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subjectLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sendButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MessagePanelLayout.createSequentialGroup()
                                .addComponent(cancelButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(fromText)
                            .addComponent(subjectText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(toText, javax.swing.GroupLayout.Alignment.TRAILING)))))
        );
        MessagePanelLayout.setVerticalGroup(
            MessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MessagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fromLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subjectLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(sendButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MessagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MessagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Handler to send the message to database
    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        //Populate message with field values
        Message msg = new Message();
        msg.mBody = bodyTextArea.getText();
        msg.mFrom = fromText.getText();
        msg.mSubject = subjectText.getText();
        msg.mTo = toText.getText().split("\\s*(;|,|\\s)\\s*");
        try {
            //Send the message
            query.sendMessage(msg);
        } catch (SQLException ex) {
            Logger.getLogger(SndMessageGUI.class.getName()).
                    log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_sendButtonActionPerformed

    //Handler to close SndMessageGUI
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    //Function for when message is in outbox so no field is editable
    void setViewOnlyMode() {
        toText.setEditable(false);
        subjectText.setEditable(false);
        bodyTextArea.setEditable(false);
        sendButton.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MessagePanel;
    private javax.swing.JTextArea bodyTextArea;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JTextField fromText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sendButton;
    private javax.swing.JLabel subjectLabel;
    private javax.swing.JTextField subjectText;
    private javax.swing.JLabel toLabel;
    private javax.swing.JTextField toText;
    // End of variables declaration//GEN-END:variables
    private final QuerySubmitter query;    
}
